name: Selenium Pytest CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Verify plugin installation
          pytest --version
          pip show pytest-rerunfailures

      - name: Install browsers
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb firefox chromium-browser

      - name: Run tests
        run: |
          xvfb-run pytest -v --reruns 2 --reruns-delay 3 --html=reports/test_report.html --self-contained-html
