name: Selenium Tests (Simple)

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  test-chrome:
    runs-on: ubuntu-latest
    name: Test with Chrome

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable
          install-chromedriver: true

      - name: Verify Chrome and ChromeDriver
        run: |
          google-chrome --version
          chromedriver --version
          which google-chrome
          which chromedriver

      - name: Create directories
        run: mkdir -p reports/screenshots reports/logs

      - name: Run tests
        env:
          BROWSER: chrome
          HEADLESS: true
          CI: true
          ENVIRONMENT: dev
        run: |
          pytest -v \
            --maxfail=1 \
            --reruns=2 \
            --reruns-delay=3 \
            --html=reports/test_report_chrome.html \
            --self-contained-html \
            --tb=short

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-chrome
          path: reports/
          retention-days: 30

  test-firefox:
    runs-on: ubuntu-latest
    name: Test with Firefox

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Setup Firefox
        uses: browser-actions/setup-firefox@v1
        with:
          firefox-version: latest

      - name: Install GeckoDriver
        run: |
          wget -q https://github.com/mozilla/geckodriver/releases/download/v0.35.0/geckodriver-v0.35.0-linux64.tar.gz
          tar -xzf geckodriver-v0.35.0-linux64.tar.gz
          sudo mv geckodriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/geckodriver
          geckodriver --version

      - name: Create directories
        run: mkdir -p reports/screenshots reports/logs

      - name: Run tests
        env:
          BROWSER: firefox
          HEADLESS: true
          CI: true
          ENVIRONMENT: dev
        run: |
          pytest -v \
            --maxfail=1 \
            --reruns=2 \
            --reruns-delay=3 \
            --html=reports/test_report_firefox.html \
            --self-contained-html \
            --tb=short

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-firefox
          path: reports/
          retention-days: 30
