name: Run Selenium Tests with Chrome

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Google Chrome & ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          CHROME_VERSION=$(google-chrome --version | grep -oP '\d+' | head -1)
          echo "Installed Chrome version: $CHROME_VERSION"
          pip install webdriver-manager
          google-chrome --version
          chromedriver --version || echo "ChromeDriver handled by webdriver-manager"

      - name: Run tests in Chrome (headless)
        env:
          BROWSER: chrome
          HEADLESS: true
        run: |
          xvfb-run pytest -v --maxfail=1 --reruns 2 --reruns-delay 3 \
            --html=reports/test_report.html --self-contained-html

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: selenium-pytest-report
          path: reports/test_report.html
