name: Selenium Pytest CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      CI: "true"
      HEADLESS: "true" # 👈 Force headless mode for Selenium
      BROWSER: "chrome"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pytest --version

      - name: Install Chrome and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip xvfb libnss3 libgconf-2-4 libxi6 libgbm-dev
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb

      - name: Verify Chrome installation
        run: google-chrome --version

      - name: Run tests
        run: |
          xvfb-run pytest -v --reruns 2 --reruns-delay 3 \
            --html=reports/test_report.html --self-contained-html
