name: Selenium Pytest CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Firefox and GeckoDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y firefox-esr
          sudo apt-get install -y geckodriver
          which firefox
          which geckodriver

      - name: Run tests in Firefox (headless)
        env:
          BROWSER: firefox
          HEADLESS: true
        run: |
          xvfb-run pytest -v --reruns 2 --reruns-delay 3 --html=reports/test_report.html --self-contained-html

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: selenium-pytest-report
          path: reports/test_report.html
